<a href="https://colab.research.google.com/github/kajal-rawat0410/summar_intership/blob/main/11june_pandas%26scipy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#pandas & scipy
#question 1
import pandas as pd

In [ ]:
#question 2
import pandas as pd
data = [100, 200, 300, 400]
s=pd.Series(data)
print(s)

0    100
1    200
2    300
3    400
dtype: int64

In [ ]:
#question 3
import pandas as pd
user_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 30, 35]}
df=pd.DataFrame(user_dict)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
#question 4
import pandas as pd
df=pd.read_csv('data.csv')
print(df)

    ID            Name  Age  Marks         City  Phone Number
0    1    Aarav Sharma   18     85        Delhi    9876543201
1    2     Priya Verma   19     78       Mumbai    9876543202
2    3     Rohit Singh   20     92       Jaipur    9876543203
3    4      Neha Gupta   18     88      Lucknow    9876543204
4    5     Karan Patel   21     74    Ahmedabad    9876543205
5    6     Ananya Jain   19     95       Indore    9876543206
6    7     Vivek Kumar   20     69        Patna    9876543207
7    8     Simran Kaur   18     81   Chandigarh    9876543208
8    9    Aditya Mehta   22     90         Pune    9876543209
9   10     Pooja Singh   19     76       Bhopal    9876543210
10  11     Rahul Yadav   20     84       Kanpur    9876543211
11  12       Sneha Roy   18     87      Kolkata    9876543212
12  13       Arjun Das   21     71  Bhubaneswar    9876543213
13  14      Kavya Nair   19     93        Kochi    9876543214
14  15    Manish Joshi   20     66     Dehradun    9876543215
15  16     Riya Kapoor   18     89        Delhi    9876543216
16  17  Saurabh Mishra   21     80      Lucknow    9876543217
17  18     Tanya Arora   19     77   Chandigarh    9876543218
18  19    Nitin Sharma   20     91       Jaipur    9876543219
19  20      Meera Iyer   18     83      Chennai    9876543220

In [ ]:
#question 5
import pandas as pd
df=pd.read_csv('data.csv')
print(df.head())

   ID          Name  Age  Marks       City  Phone Number
0   1  Aarav Sharma   18     85      Delhi    9876543201
1   2   Priya Verma   19     78     Mumbai    9876543202
2   3   Rohit Singh   20     92     Jaipur    9876543203
3   4    Neha Gupta   18     88    Lucknow    9876543204
4   5   Karan Patel   21     74  Ahmedabad    9876543205

In [ ]:
#question 6
import pandas as pd
df=pd.read_csv('data.csv')
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   ID            20 non-null     int64
 1   Name          20 non-null     object
 2   Age           20 non-null     int64
 3   Marks         20 non-null     int64
 4   City          20 non-null     object
 5   Phone Number  20 non-null     int64
dtypes: int64(4), object(2)
memory usage: 1.1+ KB
None

In [ ]:
#question 7
import pandas as pd
df=pd.read_csv('data.csv')
print(df['Marks'])

0     85
1     78
2     92
3     88
4     74
5     95
6     69
7     81
8     90
9     76
10    84
11    87
12    71
13    93
14    66
15    89
16    80
17    77
18    91
19    83
Name: Marks, dtype: int64

In [ ]:
#question 8
import pandas as pd
df=pd.read_csv('data.csv')
print(df[df['Marks']>90])

    ID          Name  Age  Marks    City  Phone Number
2    3   Rohit Singh   20     92  Jaipur    9876543203
5    6   Ananya Jain   19     95  Indore    9876543206
13  14    Kavya Nair   19     93   Kochi    9876543214
18  19  Nitin Sharma   20     91  Jaipur    9876543219

In [ ]:
#question 9
import pandas as pd
df=pd.read_csv('data.csv')
print(df.describe())

             ID        Age      Marks  Phone Number
count  20.00000  20.000000  20.000000  2.000000e+01
mean   10.50000  19.400000  82.450000  9.876543e+09
std     5.91608   1.231174   8.419745  5.916080e+00
min     1.00000  18.000000  66.000000  9.876543e+09
25%     5.75000  18.000000  76.750000  9.876543e+09
50%    10.50000  19.000000  83.500000  9.876543e+09
75%    15.25000  20.000000  89.250000  9.876543e+09
max    20.00000  22.000000  95.000000  9.876543e+09

In [ ]:
#question 10
import pandas as pd
df=pd.read_csv('data.csv')
df.to_csv('new_data.csv', index=False)

In [ ]:
#question 11 a
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj', 'Geeta'],
        'Age': [25, 30, np.nan, 28, 32],
        'score': [90, np.nan, 78, 86,np.nan]}
df=pd.DataFrame(data)
df.dropna(subset=['score'])

   Name   Age  score
0  Amit  25.0   90.0
2   NaN   NaN   78.0
3   Raj  28.0   86.0

In [ ]:
#question 11 b
data = {'Name': ['Amit', 'Sita', np.nan, 'Raj', 'Geeta'],
        'Age': [25, 30, np.nan, 28, 32],
        'score': [90, np.nan, 78, 86,np.nan]}
df=pd.DataFrame(data)
df['score']=df['score'].fillna(df['score'].mean())
print(df)

    Name   Age      score
0   Amit  25.0  90.000000
1   Sita  30.0  84.666667
2    NaN   NaN  78.000000
3    Raj  28.0  86.000000
4  Geeta  32.0  84.666667

In [ ]:
#question 12
data={'store':['Store A','Store A', 'Store B', 'Store C', 'Store D','store E'],
      'product':['Laptop','smart', 'Smartphone', 'Tablet', 'Headphones', 'Smartwatch'],
      'sale':[3478, 1000,2736, 3762, 4257, 1267]}
df=pd.DataFrame(data)
df.groupby('store')['sale'].sum()

store
Store A    4478
Store B    2736
Store C    3762
Store D    4257
store E    1267
Name: sale, dtype: int64

In [ ]:
#question 13
import pandas as pd
data1= {'emp_id' : [23,45,67,21],
       'name' : ['a','b','c','d']}
data2= {'emp_id': [23,45,67,21],
       'salary': [2345,5600,3400,2300]}

df1=pd.DataFrame(data1)
df2=pd.DataFrame(data2)
#result=df1.merge(df2,on='emp_id')
result=pd.merge(df1,df2,on='emp_id',how='inner')
print(result)

   emp_id name  salary
0      23    a    2345
1      45    b    5600
2      67    c    3400
3      21    d    2300

In [ ]:
#question 14
import numpy as np
data={'final_score':[78,34,56,47,85]}
df=pd.DataFrame(data)
df['Status'] = np.where(df['final_score'] >= 50, 'Pass', 'Fail')
print(df)

   final_score Status
0           78   Pass
1           34   Fail
2           56   Pass
3           47   Fail
4           85   Pass

In [ ]:
#question 15
import pandas as pd
data={'employee_id':[23,45,21,34]}
df=pd.DataFrame(data)
df = df.set_index('employee_id')
print(df)
df = df.reset_index()
print(df)

Empty DataFrame
Columns: []
Index: [23, 45, 21, 34]
   employee_id
0           23
1           45
2           21
3           34

In [ ]:
#sciPy
#question 1
from scipy import optimize
result = optimize.root_scalar(lambda x: x**2 - 4, bracket=[0, 3])
print(result.root)

2.0

In [ ]:
#question 2
from scipy import constants
print("value of pi=",constants.pi)
print("value of speed of light=",constants.c)
print("value of Planck's constant=",constants.h)

value of pi= 3.141592653589793
value of speed of light= 299792458.0
value of Planck's constant= 6.62607015e-34

In [ ]:
#question 3
print("55 miles into meters:",55*constants.mile)
print("10 pound weight into kg:",10*constants.pound)

55 miles into meters: 88513.91999999998
10 pound weight into kg: 4.5359237

In [ ]:
#question 4
from scipy import special
arr = [1, 8, 27, 64]
print(special.cbrt(arr))

[1. 2. 3. 4.]

In [ ]:
#question 5
from scipy import stats
dataset = [1, 2, 2, 3, 4, 4, 4, 5, 6]
print(stats.mode(dataset))

ModeResult(mode=np.int64(4), count=np.int64(3))

In [ ]:
#question 6
array=[2, 8, 32]
print("geometrical mean=",stats.gmean(array))

geometrical mean= 7.999999999999998

In [ ]:
#question 7
from scipy import linalg
matrix=[[4, 5], [2, 3]]
print("structural determinent=",linalg.det(matrix))

structural determinent= 2.0000000000000018

In [ ]:
#question 8
import numpy as np
M = np.array([[1, 2], [3, 4]])
print("inverse matrix \n",linalg.inv(M))

inverse matrix
 [[-2.   1. ]
 [ 1.5 -0.5]]

In [ ]:
#question 9
from scipy import stats
scores = [45, 60, 72, 80, 85, 90, 95, 100]
percentile = stats.scoreatpercentile(scores, 75)
print(percentile)

91.25