<a href="https://colab.research.google.com/github/kajal-rawat0410/summar_intership/blob/main/12june_regression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.linear_model import LinearRegression
data={'studyhours':[2,3,4,5],
      'marks':[40,50,60,70]}
df=pd.DataFrame(data)
x=df[['studyhours']]
y=df['marks']
model=LinearRegression()
model.fit(x,y)
predication=model.predict([[7]])
print(predication)

[90.]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [ ]:
#question 1,2
import pandas as pd
from sklearn.linear_model import LinearRegression
df=pd.read_csv('student.csv')
print(df)

    studentID    name  gender  age department  marks  attendence     city
0         101    amit    male   20        CSE   85.0        92.0    delhi
1         102   priya  female   21        CSE   78.0        88.0   mumbai
2         103   rahul    male   22        ECE   90.0        95.0    delhi
3         104    neha  female   20        ECE   67.0        75.0   jaipur
4         105   mohit    male   21        CSE   82.0        89.0    delhi
5         106  anjali  female   22         ME   91.0        96.0  lucknow
6         107   rohan    male   20         ME   73.0        80.0   jaipur
7         108  simran  female   21        CSE   88.0        94.0   mumbai
8         109   arjun    male   22        ECE   79.0        85.0    delhi
9         110   pooja  female   20         ME   86.0        91.0  lucknow
10        111   karan    male   21        CSE    NaN        87.0    delhi
11        112   sneha  female   20        ECE   84.0         NaN   mumbai

In [ ]:
#question 3
m=df.isnull().sum()
print(m)

studentID     0
name          0
gender        0
age           0
department    0
marks         1
attendence    1
city          0
dtype: int64

In [ ]:
#question 4
df['marks']=df['marks'].fillna(df['marks'].mean())
print(df)

    studentID    name  gender  age department      marks  attendence     city
0         101    amit    male   20        CSE  85.000000        92.0    delhi
1         102   priya  female   21        CSE  78.000000        88.0   mumbai
2         103   rahul    male   22        ECE  90.000000        95.0    delhi
3         104    neha  female   20        ECE  67.000000        75.0   jaipur
4         105   mohit    male   21        CSE  82.000000        89.0    delhi
5         106  anjali  female   22         ME  91.000000        96.0  lucknow
6         107   rohan    male   20         ME  73.000000        80.0   jaipur
7         108  simran  female   21        CSE  88.000000        94.0   mumbai
8         109   arjun    male   22        ECE  79.000000        85.0    delhi
9         110   pooja  female   20         ME  86.000000        91.0  lucknow
10        111   karan    male   21        CSE  82.090909        87.0    delhi
11        112   sneha  female   20        ECE  84.000000         NaN   mumbai

In [ ]:
#question 5
df['attendence']=df['attendence'].fillna(df['attendence'].mean())
print(df)

    studentID    name  gender  age department      marks  attendence     city
0         101    amit    male   20        CSE  85.000000   92.000000    delhi
1         102   priya  female   21        CSE  78.000000   88.000000   mumbai
2         103   rahul    male   22        ECE  90.000000   95.000000    delhi
3         104    neha  female   20        ECE  67.000000   75.000000   jaipur
4         105   mohit    male   21        CSE  82.000000   89.000000    delhi
5         106  anjali  female   22         ME  91.000000   96.000000  lucknow
6         107   rohan    male   20         ME  73.000000   80.000000   jaipur
7         108  simran  female   21        CSE  88.000000   94.000000   mumbai
8         109   arjun    male   22        ECE  79.000000   85.000000    delhi
9         110   pooja  female   20         ME  86.000000   91.000000  lucknow
10        111   karan    male   21        CSE  82.090909   87.000000    delhi
11        112   sneha  female   20        ECE  84.000000   88.363636   mumbai

In [ ]:
#question 6
df.drop(['name'],axis=1)

    studentID  gender  age department      marks  attendence     city
0         101    male   20        CSE  85.000000   92.000000    delhi
1         102  female   21        CSE  78.000000   88.000000   mumbai
2         103    male   22        ECE  90.000000   95.000000    delhi
3         104  female   20        ECE  67.000000   75.000000   jaipur
4         105    male   21        CSE  82.000000   89.000000    delhi
5         106  female   22         ME  91.000000   96.000000  lucknow
6         107    male   20         ME  73.000000   80.000000   jaipur
7         108  female   21        CSE  88.000000   94.000000   mumbai
8         109    male   22        ECE  79.000000   85.000000    delhi
9         110  female   20         ME  86.000000   91.000000  lucknow
10        111    male   21        CSE  82.090909   87.000000    delhi
11        112  female   20        ECE  84.000000   88.363636   mumbai

In [ ]:
#question 7
df.isnull()

    studentID   name  gender    age  department  marks  attendence   city
0       False  False   False  False       False  False       False  False
1       False  False   False  False       False  False       False  False
2       False  False   False  False       False  False       False  False
3       False  False   False  False       False  False       False  False
4       False  False   False  False       False  False       False  False
5       False  False   False  False       False  False       False  False
6       False  False   False  False       False  False       False  False
7       False  False   False  False       False  False       False  False
8       False  False   False  False       False  False       False  False
9       False  False   False  False       False  False       False  False
10      False  False   False  False       False  False       False  False
11      False  False   False  False       False  False       False  False

In [ ]:
#question 8,9,10,11,12
x=df[['attendence']]
y=df['marks']
model=LinearRegression().fit(x,y)
predication=model.predict([[92]])
print(predication)

[86.14363427]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(